### PR TITLE
Add pBuild to the Tools directory

### PR DESCRIPTION
**Pull request by sGerli**
Add pBuild to the Tools directory

### CODE REVIEW

**Comment by matthewtole** [comment]
Hi @sGerli, thanks for your contribution. Would you mind including some more information in the Markdown file? A basic overview of what pBuild is and what it does would be great.

**Comment by sGerli** [comment]
OK, I will work on that.

**Comment by sGerli** [comment]
Hi @matthewtole I updated the info, if you need anything else let me know.

**Comment by kirbyk** [comment]
Thanks for the update @sGerli! I'll add it [here](http://developer.getpebble.com/community/tools) too.

**Comment by sGerli** [comment]
Ok, Thanks

**Pull request merged**
