### PR TITLE
PinPusher PHP timeline library

### PR DESCRIPTION
**Pull request by valorin**
PinPusher is a simple Pebble Timeline Pin API wrapper for PHP, with full support for all of the Pebble Timeline API options. It is designed to be easy to use, and allow you to completely construct Timeline pins using PHP classes. This is beneficial to those with bad memories and/or IDEs that autocomplete. It also covers each individual layout case with the different requirements, so you don't need to guess what works where.

Is it also possible for PinPusher to be included within the timeline guide too?
http://developer.getpebble.com/guides/timeline/timeline-libraries/

### CODE REVIEW

**Comment by kirbyk** [comment]
@valorin this is awesome! Sorry it took so long to merge in.
I'll add it to the timeline-libraries page

**Comment by valorin** [comment]
Awesome, thanks @kirbyk :-)
I assume the list at http://developer.getpebble.com/community/libraries/ is cached and will take a few hours to be updated?

**Comment by kirbyk** [comment]
Nice catch. I added it [here](http://developer.getpebble.com/guides/timeline/timeline-libraries/), but forgot the other page. I'll fix that now.

**Comment by valorin** [comment]
:+1:

**Pull request merged**
