### PR TITLE
[WIP] php library for the pebble Timeline API

### PR DESCRIPTION
**Pull request by dav-m85**
These a lot of on-going work on this one:
- object oriented pin creation
- full test coverage
- silex bundle

Feel free to fork/issue, all help is welcomed.

NOTE: I'm posting this here in order to make it visible, even if development is not completed.

### CODE REVIEW

**Comment by matthewtole** [comment]
Hi @dav-m85. Thanks for your submission. Could you mention the WIP status of the project in the markdown file so that when we put it on the website people will know that it's not finished yet. You can submit a new PR when the library is complete and we can update it then.

**Comment by sarfata** [comment]
Hey @dav-m85 - Would you mind reaching out to me via email? Thomas@getpebble.com - I would love to discuss your plans for this library! We want to help you build it and test it!

**Comment by dav-m85** [comment]
Hi @matthewtole, I added WIP in the markdown as requested :)

**Comment by matthewtole** [comment]
Thanks @dav-m85. I will get this added to the site very soon.

**Pull request merged**
